#+title: Jake Faulkner: Mathematics Student and Programmer
#+OPTIONS: date:nil author:nil timestamp:nil num:nil toc:nil

I am a recent Master's graduate from the [[https://www.canterbury.ac.nz/][University of Canterbury]], starting a PhD at [[https://www.vub.be/][Vrije Universiteit Brussel]] in June 2023 under the supervision of [[https://researchportal.vub.be/en/persons/jan-de-beule][Jan De Beule]]. My primary research background is in [[https://en.wikipedia.org/wiki/Finite_geometry][finite geometry]], the study of the geometric systems with a finite number of points.

You can find a copy of CV here. I also have list of (hopefully growing!) publications.

Beyond Mathematics, I am also a keen programmer. I have a [[https://github.com/Triagle][GitHub profile]] where you can see some of my programming projects. Here are the highlights:
- My [[https://github.com/Triagle/dotfiles][dotfiles]], deployed using [[https://www.gnu.org/software/stow/][GNU Stow]].
- A work in progress [[https://www.gap-system.org/][GAP]] linter: [[https://github.com/Triagle/gap-lint][gap-lint]].
- An [[https://github.com/Triagle/exoplanet-deep-learning][exoplanet detector]], using CNN and RNN auto-encoders I built for one of my University courses.
- Several dead emacs configs. The current config is a [[https://github.com/doomemacs/doomemacs][Doom Emacs]] config in my dotfiles repo.

Contact me at my email: [[mailto:jake.faulkner@pg.canterbury.ac.nz][jake.faulkner@pg.canterbury.ac.nz]].
